### ISSUE TITLE
Encoding issue on Windows

### ISSUE THREAD

**Issue by Bocom** [jozsefsallai/ask#20]
Given the following sample program:
```ts
import Ask from 'https://deno.land/x/ask@1.0.5/mod.ts';

const ask = new Ask();
const { domain } = await ask.input({
  name: 'domain',
  message: 'Domän:',
});
console.log(`Domain: ${domain}`);
```

Running it on Linux, it works as expected:
```
❯ deno run menu-test.ts
? Domän:
```

But on Windows, it doesn't show the correct output:
```
❯ deno run menu-test.ts
? Dom├ñn:
```

It doesn't seem like it's an environment issue, running `console.log('Domän');` works as expected on both Windows and Linux.

**Comment by jozsefsallai** [comment]
`ask` doesn't use `console.log` under the hood, but rather writes to the output buffer directly. You can try it out like this:
```js
const prompt = new TextEncoder().encode('Domän');
await Deno.stdout.write(prompt);
```
I'm not yet sure why this issue happens only on Windows but I'll look into it.

Can you also tell me what shell you're using (i.e. PowerShell/cmd/MSYS2 bash/etc)?

**Comment by jozsefsallai** [comment]
This is the expected behavior.

`Deno.stdout.write` will write UTF-8 bytes but Windows, by default, uses UTF-16 buffers. So this isn't a problem in `ask`, it's not even a problem in Deno, it's just a Windows problem. See: https://github.com/denoland/deno/issues/6131#issuecomment-639908198

You could try writing a hacky custom writer and pass that to the `ask` options, but I wouldn't recommend doing that.

**Comment by Bocom** [comment]
Ah. Well, that's a bummer (the linked Windows thing, I mean), but thanks for looking into it!
